server.port=8080
server.servlet.context-path=/

# Aplicación
app.name=Communique
app.description=API de comunicación en tiempo real con audio
app.version=1.0.0

# Logging
logging.level.root=INFO
logging.level.com.futureprograms.communique=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# WebSocket
server.http2.enabled=true
